### ISSUE TITLE
See if it is possible to offer CPU prediction

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-topaz#10]

**Comment by delarosatrevin** [comment]
The same feature would be really useful for cryolo as well.

**Comment by pconesa** [comment]
I know Cryolo has another installation for CPU, it will be a matter of activating a different environment

**Comment by delarosatrevin** [comment]
I think the same gpu environment can be used if properly installed, so no need to new environment. I don't know exactly the flags or options to use cpu for predictions.

**Comment by pconesa** [comment]
maybe @thorstenwagner can clarify this?
Is it possible to run CPU or GPU cryolo under the same environment?

**Comment by thorstenwagner** [comment]
Sure!
You can use crYOLO (GPU) on the CPU by setting the GPU to -1 (-g -1).  However, this approach will fail with CUDA related errors when no nvidia card is installed.
Therefore I provide another CPU version for crYOLO which installes tensorflow instead if tensorflow-gpu. This works also with non nvidia machines.

You might wondering if it is not possible to use tensorflow and tensorflow-gpu in the same enviroment. I tried, but unfortunately it always chooses the tensorflow version that was installed last.

This is the information I can provide. If you know how to choose between tensorflow and tensorflow-gpu, let me know :-)

**Comment by pconesa** [comment]
Thanks @thorstenwagner , I've got no experience with tensorflow but just in case.
Have you tried this?

To make GPU invisible

export CUDA_VISIBLE_DEVICES=""
To return to normal

unset CUDA_VISIBLE_DEVICES

From https://stackoverflow.com/a/36585271

**Comment by thorstenwagner** [comment]
This is what I'm doing internally. This way you can force tensorflow-gpu to use the CPU, but if there is nvidia card available, it will crash.

**Comment by pconesa** [comment]
I see, well I'll let you know if I read, see a possible solution. Thanks!

**Comment by azazellochg** [comment]
I've been running topaz on cpu because it didn't find a gpu on my laptop :)

**Comment by delarosatrevin** [comment]
@pconesa Is there any action pending on this issue? Or can we close it?

**Comment by pconesa** [comment]
I'm ok to close it. Actually I've done it. ;-)
