### ISSUE TITLE
Concatenate installing commands with && instead of ;

### ISSUE THREAD

**Issue by dmaluenda** [scipion-em/scipion-em-topaz#5]
I would concatenate commands by `&&` instead of `;` in order to arrive to the `touch topaz_installed` only if the previous commands are not failing.

https://github.com/scipion-em/scipion-em-topaz/blob/38600d0fb2aef5d9ad31a9862b2dab066b402ce6/topaz/__init__.py#L83-L84

**Comment by rsanchezgarc** [comment]
you do not need to do the conda activate.

you can do conda install -p environment_name ....

the same for binaries

/path/to/miniconda/envs/condaEnvName/binaryName

e.g.
/path/to/miniconda/envs/topaz/python
