### ISSUE TITLE
Train /select protol required

### ISSUE THREAD

**Issue by rsanchezgarc** [scipion-em/scipion-em-topaz#8]
Now, there is only one protocol, protol_training.py that do both train and predict. Which means that, if we want to change the threshold we need to recompute everything even though the scores are stored in the sqlite.
A protocol_predict would be necessary, or at least, a  more inteligent analyze results in order to try different thresholds (see micrograph cleaner in scipion-em-xmipp)

Btw, the default threshold at -6 is too small. Should be around -1.

**Comment by delarosatrevin** [comment]
Thanks for the feedback @rsanchezgarc ! I totally agree that we should separate predict from train options. It is in this way in the similar program crYOLO. Moreover, I think that would be good to import a trained model, if the user did it outside Scipion and wants to reuse the model.

**Comment by pconesa** [comment]
Or add a threshold in a viewer and avoid the predict step.

**Comment by delarosatrevin** [comment]
@pconesa I think that having a view is independent of separating train from prediction.

**Comment by DaniDelHoyo** [comment]
Hi everyone, I digged up this issue to include the possibility of inputing a previously trained model from another protocol, which can be then retrained or used to predict directly, skipping further training. 
I have not changed anything in the analyze results, if you feel like it would be useful I can take a look at it.
